spring:
  profiles:
    #local or dev or prod
    active: prod
    include: common, datasource, logging
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8083
  ssl:
    enabled: true
    key-store: offlineMasking-test-server.p12
    key-store-password: test123
    key-store-type: PKCS12
    key-alias: offlineMasking-test-server

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 80
  ssl:
    enabled: true
    key-store: offlineMasking-test-server.p12
    key-store-password: test123
    key-store-type: PKCS12
    key-alias: offlineMasking-test-server

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80
  ssl:
    enabled: true
    key-store: offlineMasking-test-server.p12
    key-store-password: test123
    key-store-type: PKCS12
    key-alias: offlineMasking-test-server
