#-----------------------------------------------------------------------
#
#   applicaton : Base Configuation 
#   
#-----------------------------------------------------------------------

spring:
  profiles:
    #local or dev or prod
    active: local
    include: common, datasource, logging
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

mybatis:
  mapper-locations: sqlmap/sql/**/*.xml
  configuration:
    cache-enabled: true
    multiple-result-sets-enabled: true
    call-setters-on-nulls: true

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8085

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 80
---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80
